In [1]:
import numpy as np

In [2]:
list_array = np.array([5,4,6,5,4,8])
print(list_array," array type= ", type(list_array),", array data type= ", list_array.dtype,", array shape= ", list_array.shape)

[5 4 6 5 4 8]  array type=  <class 'numpy.ndarray'> , array data type=  int32 , array shape=  (6,)


In [3]:
list_array = np.array([5,4,6,5,4,8,"seyam"])
print(list_array," array type= ", type(list_array),", array data type= ", list_array.dtype,", array shape= ", list_array.shape)

['5' '4' '6' '5' '4' '8' 'seyam']  array type=  <class 'numpy.ndarray'> , array data type=  <U11 , array shape=  (7,)


***2D array***

In [4]:
array_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array_2d," array type= ", type(array_2d),", array data type= ", array_2d.dtype,", array shape= ", array_2d.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]  array type=  <class 'numpy.ndarray'> , array data type=  int32 , array shape=  (3, 3)
