In [1]:
import numpy as np

In [2]:
arr1 = np.zeros((2,3))
print(arr1, type(arr1), arr1.dtype, arr1.shape)

[[0. 0. 0.]
 [0. 0. 0.]] <class 'numpy.ndarray'> float64 (2, 3)


In [3]:
arr2 = np.zeros((2,3), dtype = "int64")
print(arr2, type(arr2), arr2.dtype, arr2.shape)

[[0 0 0]
 [0 0 0]] <class 'numpy.ndarray'> int64 (2, 3)


In [4]:
arr3 = np.ones((3,4))
print(arr3, arr3.shape)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]] (3, 4)


In [5]:
arr4 = np.full((2,3),49)
print(arr4, arr4.dtype, arr4.shape)

[[49 49 49]
 [49 49 49]] int32 (2, 3)


In [6]:
arr5 = np.eye((3), dtype = "int32")
print(arr5, arr5.shape)

[[1 0 0]
 [0 1 0]
 [0 0 1]] (3, 3)


In [7]:
arr6 = np.arange(1,11)
print(arr6, arr6.shape)

[ 1  2  3  4  5  6  7  8  9 10] (10,)


In [8]:
arr7 = np.arange(1,11, 2)#increment by 2
print(arr7, arr7.shape)

[1 3 5 7 9] (5,)


In [9]:
arr8 = np.linspace(1,100, 5)#1 thake 100 projonto but 5 vag e vag kore 5 ta value dia array banabe
print(arr8, arr8.shape)

[  1.    25.75  50.5   75.25 100.  ] (5,)
