**Array Normalization**

In [1]:
import numpy as np

In [2]:
arr = np.array([[2,3,5],[7,8,1]])
print(arr)
mean = arr.mean()
standard_deviation = arr.std()
normalization = (arr - mean)/standard_deviation
print(normalization)
print(mean)
print(standard_deviation)

[[2 3 5]
 [7 8 1]]
[[-0.91132238 -0.52075564  0.26037782]
 [ 1.04151129  1.43207802 -1.30188911]]
4.333333333333333
2.5603819159562025
