In [1]:
import numpy as np

In [10]:
arr = np.array([[5,8,9],[7,6,4],[8,7,6]])
print(arr)
print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr.ndim)
typecustarr = arr.astype(np.float64)
print(typecustarr, typecustarr.dtype)

[[5 8 9]
 [7 6 4]
 [8 7 6]]
(3, 3)
9
int32
2
[[5. 8. 9.]
 [7. 6. 4.]
 [8. 7. 6.]] float64
