In [5]:
import numpy as np

In [6]:
arr = np.array([8,9,6,4,2,6,3,9])
print(arr[3])

4


In [9]:
arr = np.array([[8,9,6],[6,3,7]])
print(arr, arr[0][2])

[[8 9 6]
 [6 3 7]] 6


**Fancy indexing**

In [10]:
arr = np.array([8,9,6,4,2,6,3,9])
ind = [0,2,4]
print(arr[ind])

[8 6 2]


In [11]:
arr = np.array([[8,9,6],[6,3,7]])
ind = [0,0,1],[0,2,1]
print(arr, arr[ind])

[[8 9 6]
 [6 3 7]] [8 6 3]


**condition**

In [12]:
arr = np.array([8,9,6,4,2,6,3,9])
print(arr[arr>4])

[8 9 6 6 9]


In [13]:
arr = np.array([8,9,6,4,2,6,3,9])
print(arr[arr %2 ==0])
print(arr[arr %2 !=0])

[8 6 4 2 6]
[9 3 9]
