In [1]:
import numpy as np

In [7]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)
sum_of_arr = arr.sum()
print(sum_of_arr)
print(np.sum(arr))
coloums_sum = arr.sum(axis = 0)
print(coloums_sum)
coloums_sum2 = np.sum(arr, axis = 0)
print(coloums_sum2)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
45
[12 15 18]
[12 15 18]
