In [1]:
import numpy as np

In [2]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr, arr.shape)

[[1 2 3]
 [4 5 6]] (2, 3)


***Reshape array***

In [3]:
reshape = arr.reshape(3,2)
print(reshape, reshape.shape)

[[1 2]
 [3 4]
 [5 6]] (3, 2)


**flatten**

In [4]:
print(reshape.flatten())

[1 2 3 4 5 6]
