In [1]:
import numpy as np

**slicing**

In [2]:
arr = np.array([1,3,5,2,6,8,84])
print(arr[3:5])
print(arr[2:])
print(arr[:4])
print(arr[:])
print(arr[1:6:2]) #increment i +=1
print(len(arr))

[2 6]
[ 5  2  6  8 84]
[1 3 5 2]
[ 1  3  5  2  6  8 84]
[3 2 8]
7
