**IN python list slicing make actual copy**

**in numpy slicing make just view**

In [1]:
list = [3,5,7,8,9,3,5,90]
print(len(list))
slicing = list[2:6]
print(slicing)
slicing[2]= 500
print(slicing)
print(list)

8
[7, 8, 9, 3]
[7, 8, 500, 3]
[3, 5, 7, 8, 9, 3, 5, 90]


**in numpy create just view**

In [2]:
import numpy as np

In [3]:
arr= np.array([3,5,7,8,9,3,5,90])
slicing = arr[2:6]
print(slicing)
slicing[2]= 500
print(slicing)
print(arr)

[7 8 9 3]
[  7   8 500   3]
[  3   5   7   8 500   3   5  90]
